# Generated by Django 5.0.4 on 2024-05-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('header', models.TextField()),
                ('description', models.TextField()),
                ('rating', models.IntegerField()),
                ('date', models.TextField()),
            ],
        ),
    ]
