# Generated by Django 5.0.4 on 2024-05-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_feedback_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_Item_I',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('game_genre', models.TextField()),
                ('all_cost', models.IntegerField()),
                ('count', models.IntegerField()),
                ('scale_game', models.IntegerField()),
                ('style_graphics', models.TextField()),
                ('mechanics', models.IntegerField()),
                ('type_graphics', models.TextField()),
            ],
        ),
    ]
